### PR TITLE
feat: added update event

### LINKED ISSUE #106: How to sum filtered result?
Hi,
I want to sum the filtered result, How to do that?
Screenshot 2566-01-25 at 16 53 56

### PR DESCRIPTION
**Pull request by kouts**
This PR adds an `update:dsData` event which emits the filtered data every time it gets updated.
Fixes #106 and #95

### CODE REVIEW

**Comment by arcadeJHS** [comment]
Currently, if I am not wrong, "update:dsData" is called also on dataset sorting.
However data returned are not sorted as displayed on UI.
Does it make sense to you to fix this? I mean: data returned by "update:dsData" should reflect what you are seeing in the table.

**Comment by arcadeJHS** [comment]
It would also be interesting also to export the functions defined in "helpers".
This could help in redefining custom components reusing existing logic: ```DatasetSearch```, for instance, which uses ```debounce```.

**Comment by kouts** [comment]
Thanks @arcadeJHS, I think it makes sense to return the sorted data. I'll check about the possibility of exporting the helpers.

**Comment by kouts** [comment]
I think there's not much point in exporting the helpers, there are utility libraries (e.g `lodash`) that provide a better alternative.

**Pull request merged**
